version: '3.4'

services:
  temp-table-backend-api:
    image: xushikuan/temp-backend:1.1
    volumes:
      - ./logs:/go/logs
    ports:
      - 18001:8080
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 1
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      start_period: 10s
      timeout: 10s
      retries: 3
      interval: 5s